# Configuration for Global Navigation Menu
header_pages:
  - index.md
  - resume.md

# Custom external links (Supported by themes like Minima or custom layouts)
nav_links:
  - title: "Ecosistema (EN)"
    url: /
  - title: "Resume (ES)"
    url: /resume.html
  - title: "GitHub Profile ↗"
    url: https://github.com/pablozunigac
