project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "!*.md"
  resources:
    - "*.pdf"
    - "**/*.pdf"

website:
  title: "Cuxhaven Labs"
  navbar:
    left:
      - href: resume.qmd
        text: Resume (US)
      - href: cv.qmd
        text: CV (LATAM)
      - href: manifesto.qmd
        text: Manifesto
    right:
      - icon: github
        href: https://github.com/pablozunigac
      - icon: envelope
        href: mailto:pablo.zuniga.c@gmail.com?subject=Professional%20Connection
      - icon: calendar-event
        href: https://calendar.notion.so/meet/cuxhavenlabs/pablo

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    toc-depth: 0
    max-width: 1800px
    date: last-modified
    date-format: "YYYY-MM-DD, HH:mm [UTC.]"
