project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "!*.md"

website:
  title: "github-website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false