project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "!*.md"
  resources:
    - "*.pdf"
    - "**/*.pdf"
    - "images/**"

website:
  title: "Cuxhaven Labs"
  favicon: images/favicon/favicon-03.png
  search: false
  navbar:
    right:
      - href: resume.qmd
        text: Resume 
      - href: cv.qmd
        text: CV (Spanish) 
      - href: manifesto.qmd
        text: Manifesto
      - text: "Connect"
        menu:
          - text: GitHub
            href: https://github.com/pablozunigac
          - text: Send an Email
            href: mailto:pablo.zuniga.c@gmail.com?subject=Professional%20Connection
          - text: Schedule a Call
            href: https://calendar.notion.so/meet/cuxhavenlabs/pablo

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    toc-depth: 0
    max-width: 1800px
